// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Com.proto

package com.module.net;

public final class Com {
  private Com() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NetOprateDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 otype = 1;
    /**
     * <code>required int32 otype = 1;</code>
     *
     * <pre>
     ** 类型 
     * </pre>
     */
    boolean hasOtype();
    /**
     * <code>required int32 otype = 1;</code>
     *
     * <pre>
     ** 类型 
     * </pre>
     */
    int getOtype();

    // optional int32 uid = 2;
    /**
     * <code>optional int32 uid = 2;</code>
     */
    boolean hasUid();
    /**
     * <code>optional int32 uid = 2;</code>
     */
    int getUid();

    // optional int32 dval = 3;
    /**
     * <code>optional int32 dval = 3;</code>
     */
    boolean hasDval();
    /**
     * <code>optional int32 dval = 3;</code>
     */
    int getDval();

    // optional int32 flag = 4;
    /**
     * <code>optional int32 flag = 4;</code>
     */
    boolean hasFlag();
    /**
     * <code>optional int32 flag = 4;</code>
     */
    int getFlag();

    // repeated int32 dlist = 5;
    /**
     * <code>repeated int32 dlist = 5;</code>
     */
    java.util.List<java.lang.Integer> getDlistList();
    /**
     * <code>repeated int32 dlist = 5;</code>
     */
    int getDlistCount();
    /**
     * <code>repeated int32 dlist = 5;</code>
     */
    int getDlist(int index);

    // repeated .NetKVData kvData = 6;
    /**
     * <code>repeated .NetKVData kvData = 6;</code>
     */
    java.util.List<com.module.net.Com.NetKVData> 
        getKvDataList();
    /**
     * <code>repeated .NetKVData kvData = 6;</code>
     */
    com.module.net.Com.NetKVData getKvData(int index);
    /**
     * <code>repeated .NetKVData kvData = 6;</code>
     */
    int getKvDataCount();
    /**
     * <code>repeated .NetKVData kvData = 6;</code>
     */
    java.util.List<? extends com.module.net.Com.NetKVDataOrBuilder> 
        getKvDataOrBuilderList();
    /**
     * <code>repeated .NetKVData kvData = 6;</code>
     */
    com.module.net.Com.NetKVDataOrBuilder getKvDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code NetOprateData}
   */
  public static final class NetOprateData extends
      com.google.protobuf.GeneratedMessage
      implements NetOprateDataOrBuilder {
    // Use NetOprateData.newBuilder() to construct.
    private NetOprateData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NetOprateData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NetOprateData defaultInstance;
    public static NetOprateData getDefaultInstance() {
      return defaultInstance;
    }

    public NetOprateData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NetOprateData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              otype_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              uid_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              dval_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              flag_ = input.readInt32();
              break;
            }
            case 40: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                dlist_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000010;
              }
              dlist_.add(input.readInt32());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                dlist_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                dlist_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                kvData_ = new java.util.ArrayList<com.module.net.Com.NetKVData>();
                mutable_bitField0_ |= 0x00000020;
              }
              kvData_.add(input.readMessage(com.module.net.Com.NetKVData.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          dlist_ = java.util.Collections.unmodifiableList(dlist_);
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          kvData_ = java.util.Collections.unmodifiableList(kvData_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.module.net.Com.internal_static_NetOprateData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.module.net.Com.internal_static_NetOprateData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.module.net.Com.NetOprateData.class, com.module.net.Com.NetOprateData.Builder.class);
    }

    public static com.google.protobuf.Parser<NetOprateData> PARSER =
        new com.google.protobuf.AbstractParser<NetOprateData>() {
      public NetOprateData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NetOprateData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NetOprateData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 otype = 1;
    public static final int OTYPE_FIELD_NUMBER = 1;
    private int otype_;
    /**
     * <code>required int32 otype = 1;</code>
     *
     * <pre>
     ** 类型 
     * </pre>
     */
    public boolean hasOtype() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 otype = 1;</code>
     *
     * <pre>
     ** 类型 
     * </pre>
     */
    public int getOtype() {
      return otype_;
    }

    // optional int32 uid = 2;
    public static final int UID_FIELD_NUMBER = 2;
    private int uid_;
    /**
     * <code>optional int32 uid = 2;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 uid = 2;</code>
     */
    public int getUid() {
      return uid_;
    }

    // optional int32 dval = 3;
    public static final int DVAL_FIELD_NUMBER = 3;
    private int dval_;
    /**
     * <code>optional int32 dval = 3;</code>
     */
    public boolean hasDval() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 dval = 3;</code>
     */
    public int getDval() {
      return dval_;
    }

    // optional int32 flag = 4;
    public static final int FLAG_FIELD_NUMBER = 4;
    private int flag_;
    /**
     * <code>optional int32 flag = 4;</code>
     */
    public boolean hasFlag() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 flag = 4;</code>
     */
    public int getFlag() {
      return flag_;
    }

    // repeated int32 dlist = 5;
    public static final int DLIST_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Integer> dlist_;
    /**
     * <code>repeated int32 dlist = 5;</code>
     */
    public java.util.List<java.lang.Integer>
        getDlistList() {
      return dlist_;
    }
    /**
     * <code>repeated int32 dlist = 5;</code>
     */
    public int getDlistCount() {
      return dlist_.size();
    }
    /**
     * <code>repeated int32 dlist = 5;</code>
     */
    public int getDlist(int index) {
      return dlist_.get(index);
    }

    // repeated .NetKVData kvData = 6;
    public static final int KVDATA_FIELD_NUMBER = 6;
    private java.util.List<com.module.net.Com.NetKVData> kvData_;
    /**
     * <code>repeated .NetKVData kvData = 6;</code>
     */
    public java.util.List<com.module.net.Com.NetKVData> getKvDataList() {
      return kvData_;
    }
    /**
     * <code>repeated .NetKVData kvData = 6;</code>
     */
    public java.util.List<? extends com.module.net.Com.NetKVDataOrBuilder> 
        getKvDataOrBuilderList() {
      return kvData_;
    }
    /**
     * <code>repeated .NetKVData kvData = 6;</code>
     */
    public int getKvDataCount() {
      return kvData_.size();
    }
    /**
     * <code>repeated .NetKVData kvData = 6;</code>
     */
    public com.module.net.Com.NetKVData getKvData(int index) {
      return kvData_.get(index);
    }
    /**
     * <code>repeated .NetKVData kvData = 6;</code>
     */
    public com.module.net.Com.NetKVDataOrBuilder getKvDataOrBuilder(
        int index) {
      return kvData_.get(index);
    }

    private void initFields() {
      otype_ = 0;
      uid_ = 0;
      dval_ = 0;
      flag_ = 0;
      dlist_ = java.util.Collections.emptyList();
      kvData_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasOtype()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, otype_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, uid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, dval_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, flag_);
      }
      for (int i = 0; i < dlist_.size(); i++) {
        output.writeInt32(5, dlist_.get(i));
      }
      for (int i = 0; i < kvData_.size(); i++) {
        output.writeMessage(6, kvData_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, otype_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, uid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, dval_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, flag_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < dlist_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dlist_.get(i));
        }
        size += dataSize;
        size += 1 * getDlistList().size();
      }
      for (int i = 0; i < kvData_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, kvData_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.module.net.Com.NetOprateData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.module.net.Com.NetOprateData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.module.net.Com.NetOprateData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.module.net.Com.NetOprateData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.module.net.Com.NetOprateData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.module.net.Com.NetOprateData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.module.net.Com.NetOprateData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.module.net.Com.NetOprateData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.module.net.Com.NetOprateData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.module.net.Com.NetOprateData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.module.net.Com.NetOprateData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NetOprateData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.module.net.Com.NetOprateDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.module.net.Com.internal_static_NetOprateData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.module.net.Com.internal_static_NetOprateData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.module.net.Com.NetOprateData.class, com.module.net.Com.NetOprateData.Builder.class);
      }

      // Construct using com.module.net.Com.NetOprateData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getKvDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        otype_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        dval_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        flag_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        dlist_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        if (kvDataBuilder_ == null) {
          kvData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          kvDataBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.module.net.Com.internal_static_NetOprateData_descriptor;
      }

      public com.module.net.Com.NetOprateData getDefaultInstanceForType() {
        return com.module.net.Com.NetOprateData.getDefaultInstance();
      }

      public com.module.net.Com.NetOprateData build() {
        com.module.net.Com.NetOprateData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.module.net.Com.NetOprateData buildPartial() {
        com.module.net.Com.NetOprateData result = new com.module.net.Com.NetOprateData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.otype_ = otype_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dval_ = dval_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.flag_ = flag_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          dlist_ = java.util.Collections.unmodifiableList(dlist_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.dlist_ = dlist_;
        if (kvDataBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            kvData_ = java.util.Collections.unmodifiableList(kvData_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.kvData_ = kvData_;
        } else {
          result.kvData_ = kvDataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.module.net.Com.NetOprateData) {
          return mergeFrom((com.module.net.Com.NetOprateData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.module.net.Com.NetOprateData other) {
        if (other == com.module.net.Com.NetOprateData.getDefaultInstance()) return this;
        if (other.hasOtype()) {
          setOtype(other.getOtype());
        }
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasDval()) {
          setDval(other.getDval());
        }
        if (other.hasFlag()) {
          setFlag(other.getFlag());
        }
        if (!other.dlist_.isEmpty()) {
          if (dlist_.isEmpty()) {
            dlist_ = other.dlist_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureDlistIsMutable();
            dlist_.addAll(other.dlist_);
          }
          onChanged();
        }
        if (kvDataBuilder_ == null) {
          if (!other.kvData_.isEmpty()) {
            if (kvData_.isEmpty()) {
              kvData_ = other.kvData_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureKvDataIsMutable();
              kvData_.addAll(other.kvData_);
            }
            onChanged();
          }
        } else {
          if (!other.kvData_.isEmpty()) {
            if (kvDataBuilder_.isEmpty()) {
              kvDataBuilder_.dispose();
              kvDataBuilder_ = null;
              kvData_ = other.kvData_;
              bitField0_ = (bitField0_ & ~0x00000020);
              kvDataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getKvDataFieldBuilder() : null;
            } else {
              kvDataBuilder_.addAllMessages(other.kvData_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOtype()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.module.net.Com.NetOprateData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.module.net.Com.NetOprateData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 otype = 1;
      private int otype_ ;
      /**
       * <code>required int32 otype = 1;</code>
       *
       * <pre>
       ** 类型 
       * </pre>
       */
      public boolean hasOtype() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 otype = 1;</code>
       *
       * <pre>
       ** 类型 
       * </pre>
       */
      public int getOtype() {
        return otype_;
      }
      /**
       * <code>required int32 otype = 1;</code>
       *
       * <pre>
       ** 类型 
       * </pre>
       */
      public Builder setOtype(int value) {
        bitField0_ |= 0x00000001;
        otype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 otype = 1;</code>
       *
       * <pre>
       ** 类型 
       * </pre>
       */
      public Builder clearOtype() {
        bitField0_ = (bitField0_ & ~0x00000001);
        otype_ = 0;
        onChanged();
        return this;
      }

      // optional int32 uid = 2;
      private int uid_ ;
      /**
       * <code>optional int32 uid = 2;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 uid = 2;</code>
       */
      public int getUid() {
        return uid_;
      }
      /**
       * <code>optional int32 uid = 2;</code>
       */
      public Builder setUid(int value) {
        bitField0_ |= 0x00000002;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 uid = 2;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uid_ = 0;
        onChanged();
        return this;
      }

      // optional int32 dval = 3;
      private int dval_ ;
      /**
       * <code>optional int32 dval = 3;</code>
       */
      public boolean hasDval() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 dval = 3;</code>
       */
      public int getDval() {
        return dval_;
      }
      /**
       * <code>optional int32 dval = 3;</code>
       */
      public Builder setDval(int value) {
        bitField0_ |= 0x00000004;
        dval_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 dval = 3;</code>
       */
      public Builder clearDval() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dval_ = 0;
        onChanged();
        return this;
      }

      // optional int32 flag = 4;
      private int flag_ ;
      /**
       * <code>optional int32 flag = 4;</code>
       */
      public boolean hasFlag() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 flag = 4;</code>
       */
      public int getFlag() {
        return flag_;
      }
      /**
       * <code>optional int32 flag = 4;</code>
       */
      public Builder setFlag(int value) {
        bitField0_ |= 0x00000008;
        flag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 flag = 4;</code>
       */
      public Builder clearFlag() {
        bitField0_ = (bitField0_ & ~0x00000008);
        flag_ = 0;
        onChanged();
        return this;
      }

      // repeated int32 dlist = 5;
      private java.util.List<java.lang.Integer> dlist_ = java.util.Collections.emptyList();
      private void ensureDlistIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          dlist_ = new java.util.ArrayList<java.lang.Integer>(dlist_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated int32 dlist = 5;</code>
       */
      public java.util.List<java.lang.Integer>
          getDlistList() {
        return java.util.Collections.unmodifiableList(dlist_);
      }
      /**
       * <code>repeated int32 dlist = 5;</code>
       */
      public int getDlistCount() {
        return dlist_.size();
      }
      /**
       * <code>repeated int32 dlist = 5;</code>
       */
      public int getDlist(int index) {
        return dlist_.get(index);
      }
      /**
       * <code>repeated int32 dlist = 5;</code>
       */
      public Builder setDlist(
          int index, int value) {
        ensureDlistIsMutable();
        dlist_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 dlist = 5;</code>
       */
      public Builder addDlist(int value) {
        ensureDlistIsMutable();
        dlist_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 dlist = 5;</code>
       */
      public Builder addAllDlist(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureDlistIsMutable();
        super.addAll(values, dlist_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 dlist = 5;</code>
       */
      public Builder clearDlist() {
        dlist_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      // repeated .NetKVData kvData = 6;
      private java.util.List<com.module.net.Com.NetKVData> kvData_ =
        java.util.Collections.emptyList();
      private void ensureKvDataIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          kvData_ = new java.util.ArrayList<com.module.net.Com.NetKVData>(kvData_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.module.net.Com.NetKVData, com.module.net.Com.NetKVData.Builder, com.module.net.Com.NetKVDataOrBuilder> kvDataBuilder_;

      /**
       * <code>repeated .NetKVData kvData = 6;</code>
       */
      public java.util.List<com.module.net.Com.NetKVData> getKvDataList() {
        if (kvDataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(kvData_);
        } else {
          return kvDataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .NetKVData kvData = 6;</code>
       */
      public int getKvDataCount() {
        if (kvDataBuilder_ == null) {
          return kvData_.size();
        } else {
          return kvDataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .NetKVData kvData = 6;</code>
       */
      public com.module.net.Com.NetKVData getKvData(int index) {
        if (kvDataBuilder_ == null) {
          return kvData_.get(index);
        } else {
          return kvDataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .NetKVData kvData = 6;</code>
       */
      public Builder setKvData(
          int index, com.module.net.Com.NetKVData value) {
        if (kvDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKvDataIsMutable();
          kvData_.set(index, value);
          onChanged();
        } else {
          kvDataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NetKVData kvData = 6;</code>
       */
      public Builder setKvData(
          int index, com.module.net.Com.NetKVData.Builder builderForValue) {
        if (kvDataBuilder_ == null) {
          ensureKvDataIsMutable();
          kvData_.set(index, builderForValue.build());
          onChanged();
        } else {
          kvDataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NetKVData kvData = 6;</code>
       */
      public Builder addKvData(com.module.net.Com.NetKVData value) {
        if (kvDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKvDataIsMutable();
          kvData_.add(value);
          onChanged();
        } else {
          kvDataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .NetKVData kvData = 6;</code>
       */
      public Builder addKvData(
          int index, com.module.net.Com.NetKVData value) {
        if (kvDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKvDataIsMutable();
          kvData_.add(index, value);
          onChanged();
        } else {
          kvDataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NetKVData kvData = 6;</code>
       */
      public Builder addKvData(
          com.module.net.Com.NetKVData.Builder builderForValue) {
        if (kvDataBuilder_ == null) {
          ensureKvDataIsMutable();
          kvData_.add(builderForValue.build());
          onChanged();
        } else {
          kvDataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NetKVData kvData = 6;</code>
       */
      public Builder addKvData(
          int index, com.module.net.Com.NetKVData.Builder builderForValue) {
        if (kvDataBuilder_ == null) {
          ensureKvDataIsMutable();
          kvData_.add(index, builderForValue.build());
          onChanged();
        } else {
          kvDataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NetKVData kvData = 6;</code>
       */
      public Builder addAllKvData(
          java.lang.Iterable<? extends com.module.net.Com.NetKVData> values) {
        if (kvDataBuilder_ == null) {
          ensureKvDataIsMutable();
          super.addAll(values, kvData_);
          onChanged();
        } else {
          kvDataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .NetKVData kvData = 6;</code>
       */
      public Builder clearKvData() {
        if (kvDataBuilder_ == null) {
          kvData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          kvDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .NetKVData kvData = 6;</code>
       */
      public Builder removeKvData(int index) {
        if (kvDataBuilder_ == null) {
          ensureKvDataIsMutable();
          kvData_.remove(index);
          onChanged();
        } else {
          kvDataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .NetKVData kvData = 6;</code>
       */
      public com.module.net.Com.NetKVData.Builder getKvDataBuilder(
          int index) {
        return getKvDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .NetKVData kvData = 6;</code>
       */
      public com.module.net.Com.NetKVDataOrBuilder getKvDataOrBuilder(
          int index) {
        if (kvDataBuilder_ == null) {
          return kvData_.get(index);  } else {
          return kvDataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .NetKVData kvData = 6;</code>
       */
      public java.util.List<? extends com.module.net.Com.NetKVDataOrBuilder> 
           getKvDataOrBuilderList() {
        if (kvDataBuilder_ != null) {
          return kvDataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(kvData_);
        }
      }
      /**
       * <code>repeated .NetKVData kvData = 6;</code>
       */
      public com.module.net.Com.NetKVData.Builder addKvDataBuilder() {
        return getKvDataFieldBuilder().addBuilder(
            com.module.net.Com.NetKVData.getDefaultInstance());
      }
      /**
       * <code>repeated .NetKVData kvData = 6;</code>
       */
      public com.module.net.Com.NetKVData.Builder addKvDataBuilder(
          int index) {
        return getKvDataFieldBuilder().addBuilder(
            index, com.module.net.Com.NetKVData.getDefaultInstance());
      }
      /**
       * <code>repeated .NetKVData kvData = 6;</code>
       */
      public java.util.List<com.module.net.Com.NetKVData.Builder> 
           getKvDataBuilderList() {
        return getKvDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.module.net.Com.NetKVData, com.module.net.Com.NetKVData.Builder, com.module.net.Com.NetKVDataOrBuilder> 
          getKvDataFieldBuilder() {
        if (kvDataBuilder_ == null) {
          kvDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.module.net.Com.NetKVData, com.module.net.Com.NetKVData.Builder, com.module.net.Com.NetKVDataOrBuilder>(
                  kvData_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          kvData_ = null;
        }
        return kvDataBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:NetOprateData)
    }

    static {
      defaultInstance = new NetOprateData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NetOprateData)
  }

  public interface NetKVDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 k = 1;
    /**
     * <code>optional int32 k = 1;</code>
     */
    boolean hasK();
    /**
     * <code>optional int32 k = 1;</code>
     */
    int getK();

    // optional int32 v = 2;
    /**
     * <code>optional int32 v = 2;</code>
     *
     * <pre>
     ** value 
     * </pre>
     */
    boolean hasV();
    /**
     * <code>optional int32 v = 2;</code>
     *
     * <pre>
     ** value 
     * </pre>
     */
    int getV();

    // repeated int32 dlist = 3;
    /**
     * <code>repeated int32 dlist = 3;</code>
     *
     * <pre>
     ** list 
     * </pre>
     */
    java.util.List<java.lang.Integer> getDlistList();
    /**
     * <code>repeated int32 dlist = 3;</code>
     *
     * <pre>
     ** list 
     * </pre>
     */
    int getDlistCount();
    /**
     * <code>repeated int32 dlist = 3;</code>
     *
     * <pre>
     ** list 
     * </pre>
     */
    int getDlist(int index);
  }
  /**
   * Protobuf type {@code NetKVData}
   */
  public static final class NetKVData extends
      com.google.protobuf.GeneratedMessage
      implements NetKVDataOrBuilder {
    // Use NetKVData.newBuilder() to construct.
    private NetKVData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NetKVData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NetKVData defaultInstance;
    public static NetKVData getDefaultInstance() {
      return defaultInstance;
    }

    public NetKVData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NetKVData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              k_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              v_ = input.readInt32();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                dlist_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              dlist_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                dlist_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                dlist_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          dlist_ = java.util.Collections.unmodifiableList(dlist_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.module.net.Com.internal_static_NetKVData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.module.net.Com.internal_static_NetKVData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.module.net.Com.NetKVData.class, com.module.net.Com.NetKVData.Builder.class);
    }

    public static com.google.protobuf.Parser<NetKVData> PARSER =
        new com.google.protobuf.AbstractParser<NetKVData>() {
      public NetKVData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NetKVData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NetKVData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 k = 1;
    public static final int K_FIELD_NUMBER = 1;
    private int k_;
    /**
     * <code>optional int32 k = 1;</code>
     */
    public boolean hasK() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 k = 1;</code>
     */
    public int getK() {
      return k_;
    }

    // optional int32 v = 2;
    public static final int V_FIELD_NUMBER = 2;
    private int v_;
    /**
     * <code>optional int32 v = 2;</code>
     *
     * <pre>
     ** value 
     * </pre>
     */
    public boolean hasV() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 v = 2;</code>
     *
     * <pre>
     ** value 
     * </pre>
     */
    public int getV() {
      return v_;
    }

    // repeated int32 dlist = 3;
    public static final int DLIST_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> dlist_;
    /**
     * <code>repeated int32 dlist = 3;</code>
     *
     * <pre>
     ** list 
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getDlistList() {
      return dlist_;
    }
    /**
     * <code>repeated int32 dlist = 3;</code>
     *
     * <pre>
     ** list 
     * </pre>
     */
    public int getDlistCount() {
      return dlist_.size();
    }
    /**
     * <code>repeated int32 dlist = 3;</code>
     *
     * <pre>
     ** list 
     * </pre>
     */
    public int getDlist(int index) {
      return dlist_.get(index);
    }

    private void initFields() {
      k_ = 0;
      v_ = 0;
      dlist_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, k_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, v_);
      }
      for (int i = 0; i < dlist_.size(); i++) {
        output.writeInt32(3, dlist_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, k_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, v_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < dlist_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dlist_.get(i));
        }
        size += dataSize;
        size += 1 * getDlistList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.module.net.Com.NetKVData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.module.net.Com.NetKVData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.module.net.Com.NetKVData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.module.net.Com.NetKVData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.module.net.Com.NetKVData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.module.net.Com.NetKVData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.module.net.Com.NetKVData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.module.net.Com.NetKVData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.module.net.Com.NetKVData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.module.net.Com.NetKVData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.module.net.Com.NetKVData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NetKVData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.module.net.Com.NetKVDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.module.net.Com.internal_static_NetKVData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.module.net.Com.internal_static_NetKVData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.module.net.Com.NetKVData.class, com.module.net.Com.NetKVData.Builder.class);
      }

      // Construct using com.module.net.Com.NetKVData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        k_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        v_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        dlist_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.module.net.Com.internal_static_NetKVData_descriptor;
      }

      public com.module.net.Com.NetKVData getDefaultInstanceForType() {
        return com.module.net.Com.NetKVData.getDefaultInstance();
      }

      public com.module.net.Com.NetKVData build() {
        com.module.net.Com.NetKVData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.module.net.Com.NetKVData buildPartial() {
        com.module.net.Com.NetKVData result = new com.module.net.Com.NetKVData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.k_ = k_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.v_ = v_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          dlist_ = java.util.Collections.unmodifiableList(dlist_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.dlist_ = dlist_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.module.net.Com.NetKVData) {
          return mergeFrom((com.module.net.Com.NetKVData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.module.net.Com.NetKVData other) {
        if (other == com.module.net.Com.NetKVData.getDefaultInstance()) return this;
        if (other.hasK()) {
          setK(other.getK());
        }
        if (other.hasV()) {
          setV(other.getV());
        }
        if (!other.dlist_.isEmpty()) {
          if (dlist_.isEmpty()) {
            dlist_ = other.dlist_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureDlistIsMutable();
            dlist_.addAll(other.dlist_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.module.net.Com.NetKVData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.module.net.Com.NetKVData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 k = 1;
      private int k_ ;
      /**
       * <code>optional int32 k = 1;</code>
       */
      public boolean hasK() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 k = 1;</code>
       */
      public int getK() {
        return k_;
      }
      /**
       * <code>optional int32 k = 1;</code>
       */
      public Builder setK(int value) {
        bitField0_ |= 0x00000001;
        k_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 k = 1;</code>
       */
      public Builder clearK() {
        bitField0_ = (bitField0_ & ~0x00000001);
        k_ = 0;
        onChanged();
        return this;
      }

      // optional int32 v = 2;
      private int v_ ;
      /**
       * <code>optional int32 v = 2;</code>
       *
       * <pre>
       ** value 
       * </pre>
       */
      public boolean hasV() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 v = 2;</code>
       *
       * <pre>
       ** value 
       * </pre>
       */
      public int getV() {
        return v_;
      }
      /**
       * <code>optional int32 v = 2;</code>
       *
       * <pre>
       ** value 
       * </pre>
       */
      public Builder setV(int value) {
        bitField0_ |= 0x00000002;
        v_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 v = 2;</code>
       *
       * <pre>
       ** value 
       * </pre>
       */
      public Builder clearV() {
        bitField0_ = (bitField0_ & ~0x00000002);
        v_ = 0;
        onChanged();
        return this;
      }

      // repeated int32 dlist = 3;
      private java.util.List<java.lang.Integer> dlist_ = java.util.Collections.emptyList();
      private void ensureDlistIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          dlist_ = new java.util.ArrayList<java.lang.Integer>(dlist_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 dlist = 3;</code>
       *
       * <pre>
       ** list 
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getDlistList() {
        return java.util.Collections.unmodifiableList(dlist_);
      }
      /**
       * <code>repeated int32 dlist = 3;</code>
       *
       * <pre>
       ** list 
       * </pre>
       */
      public int getDlistCount() {
        return dlist_.size();
      }
      /**
       * <code>repeated int32 dlist = 3;</code>
       *
       * <pre>
       ** list 
       * </pre>
       */
      public int getDlist(int index) {
        return dlist_.get(index);
      }
      /**
       * <code>repeated int32 dlist = 3;</code>
       *
       * <pre>
       ** list 
       * </pre>
       */
      public Builder setDlist(
          int index, int value) {
        ensureDlistIsMutable();
        dlist_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 dlist = 3;</code>
       *
       * <pre>
       ** list 
       * </pre>
       */
      public Builder addDlist(int value) {
        ensureDlistIsMutable();
        dlist_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 dlist = 3;</code>
       *
       * <pre>
       ** list 
       * </pre>
       */
      public Builder addAllDlist(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureDlistIsMutable();
        super.addAll(values, dlist_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 dlist = 3;</code>
       *
       * <pre>
       ** list 
       * </pre>
       */
      public Builder clearDlist() {
        dlist_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NetKVData)
    }

    static {
      defaultInstance = new NetKVData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NetKVData)
  }

  public interface NetResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 status = 1;
    /**
     * <code>optional int32 status = 1;</code>
     */
    boolean hasStatus();
    /**
     * <code>optional int32 status = 1;</code>
     */
    int getStatus();

    // repeated .NetOprateData operateDatas = 2;
    /**
     * <code>repeated .NetOprateData operateDatas = 2;</code>
     *
     * <pre>
     ** 关联 
     * </pre>
     */
    java.util.List<com.module.net.Com.NetOprateData> 
        getOperateDatasList();
    /**
     * <code>repeated .NetOprateData operateDatas = 2;</code>
     *
     * <pre>
     ** 关联 
     * </pre>
     */
    com.module.net.Com.NetOprateData getOperateDatas(int index);
    /**
     * <code>repeated .NetOprateData operateDatas = 2;</code>
     *
     * <pre>
     ** 关联 
     * </pre>
     */
    int getOperateDatasCount();
    /**
     * <code>repeated .NetOprateData operateDatas = 2;</code>
     *
     * <pre>
     ** 关联 
     * </pre>
     */
    java.util.List<? extends com.module.net.Com.NetOprateDataOrBuilder> 
        getOperateDatasOrBuilderList();
    /**
     * <code>repeated .NetOprateData operateDatas = 2;</code>
     *
     * <pre>
     ** 关联 
     * </pre>
     */
    com.module.net.Com.NetOprateDataOrBuilder getOperateDatasOrBuilder(
        int index);

    // required int32 retStatus = 3;
    /**
     * <code>required int32 retStatus = 3;</code>
     *
     * <pre>
     ** 状态 
     * </pre>
     */
    boolean hasRetStatus();
    /**
     * <code>required int32 retStatus = 3;</code>
     *
     * <pre>
     ** 状态 
     * </pre>
     */
    int getRetStatus();

    // optional int32 step = 4;
    /**
     * <code>optional int32 step = 4;</code>
     */
    boolean hasStep();
    /**
     * <code>optional int32 step = 4;</code>
     */
    int getStep();
  }
  /**
   * Protobuf type {@code NetResponse}
   */
  public static final class NetResponse extends
      com.google.protobuf.GeneratedMessage
      implements NetResponseOrBuilder {
    // Use NetResponse.newBuilder() to construct.
    private NetResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NetResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NetResponse defaultInstance;
    public static NetResponse getDefaultInstance() {
      return defaultInstance;
    }

    public NetResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NetResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              status_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                operateDatas_ = new java.util.ArrayList<com.module.net.Com.NetOprateData>();
                mutable_bitField0_ |= 0x00000002;
              }
              operateDatas_.add(input.readMessage(com.module.net.Com.NetOprateData.PARSER, extensionRegistry));
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              retStatus_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              step_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          operateDatas_ = java.util.Collections.unmodifiableList(operateDatas_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.module.net.Com.internal_static_NetResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.module.net.Com.internal_static_NetResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.module.net.Com.NetResponse.class, com.module.net.Com.NetResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<NetResponse> PARSER =
        new com.google.protobuf.AbstractParser<NetResponse>() {
      public NetResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NetResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NetResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 status = 1;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>optional int32 status = 1;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 status = 1;</code>
     */
    public int getStatus() {
      return status_;
    }

    // repeated .NetOprateData operateDatas = 2;
    public static final int OPERATEDATAS_FIELD_NUMBER = 2;
    private java.util.List<com.module.net.Com.NetOprateData> operateDatas_;
    /**
     * <code>repeated .NetOprateData operateDatas = 2;</code>
     *
     * <pre>
     ** 关联 
     * </pre>
     */
    public java.util.List<com.module.net.Com.NetOprateData> getOperateDatasList() {
      return operateDatas_;
    }
    /**
     * <code>repeated .NetOprateData operateDatas = 2;</code>
     *
     * <pre>
     ** 关联 
     * </pre>
     */
    public java.util.List<? extends com.module.net.Com.NetOprateDataOrBuilder> 
        getOperateDatasOrBuilderList() {
      return operateDatas_;
    }
    /**
     * <code>repeated .NetOprateData operateDatas = 2;</code>
     *
     * <pre>
     ** 关联 
     * </pre>
     */
    public int getOperateDatasCount() {
      return operateDatas_.size();
    }
    /**
     * <code>repeated .NetOprateData operateDatas = 2;</code>
     *
     * <pre>
     ** 关联 
     * </pre>
     */
    public com.module.net.Com.NetOprateData getOperateDatas(int index) {
      return operateDatas_.get(index);
    }
    /**
     * <code>repeated .NetOprateData operateDatas = 2;</code>
     *
     * <pre>
     ** 关联 
     * </pre>
     */
    public com.module.net.Com.NetOprateDataOrBuilder getOperateDatasOrBuilder(
        int index) {
      return operateDatas_.get(index);
    }

    // required int32 retStatus = 3;
    public static final int RETSTATUS_FIELD_NUMBER = 3;
    private int retStatus_;
    /**
     * <code>required int32 retStatus = 3;</code>
     *
     * <pre>
     ** 状态 
     * </pre>
     */
    public boolean hasRetStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 retStatus = 3;</code>
     *
     * <pre>
     ** 状态 
     * </pre>
     */
    public int getRetStatus() {
      return retStatus_;
    }

    // optional int32 step = 4;
    public static final int STEP_FIELD_NUMBER = 4;
    private int step_;
    /**
     * <code>optional int32 step = 4;</code>
     */
    public boolean hasStep() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 step = 4;</code>
     */
    public int getStep() {
      return step_;
    }

    private void initFields() {
      status_ = 0;
      operateDatas_ = java.util.Collections.emptyList();
      retStatus_ = 0;
      step_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRetStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getOperateDatasCount(); i++) {
        if (!getOperateDatas(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, status_);
      }
      for (int i = 0; i < operateDatas_.size(); i++) {
        output.writeMessage(2, operateDatas_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, retStatus_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, step_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, status_);
      }
      for (int i = 0; i < operateDatas_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, operateDatas_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, retStatus_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, step_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.module.net.Com.NetResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.module.net.Com.NetResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.module.net.Com.NetResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.module.net.Com.NetResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.module.net.Com.NetResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.module.net.Com.NetResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.module.net.Com.NetResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.module.net.Com.NetResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.module.net.Com.NetResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.module.net.Com.NetResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.module.net.Com.NetResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NetResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.module.net.Com.NetResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.module.net.Com.internal_static_NetResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.module.net.Com.internal_static_NetResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.module.net.Com.NetResponse.class, com.module.net.Com.NetResponse.Builder.class);
      }

      // Construct using com.module.net.Com.NetResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getOperateDatasFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (operateDatasBuilder_ == null) {
          operateDatas_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          operateDatasBuilder_.clear();
        }
        retStatus_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        step_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.module.net.Com.internal_static_NetResponse_descriptor;
      }

      public com.module.net.Com.NetResponse getDefaultInstanceForType() {
        return com.module.net.Com.NetResponse.getDefaultInstance();
      }

      public com.module.net.Com.NetResponse build() {
        com.module.net.Com.NetResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.module.net.Com.NetResponse buildPartial() {
        com.module.net.Com.NetResponse result = new com.module.net.Com.NetResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.status_ = status_;
        if (operateDatasBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            operateDatas_ = java.util.Collections.unmodifiableList(operateDatas_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.operateDatas_ = operateDatas_;
        } else {
          result.operateDatas_ = operateDatasBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.retStatus_ = retStatus_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.step_ = step_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.module.net.Com.NetResponse) {
          return mergeFrom((com.module.net.Com.NetResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.module.net.Com.NetResponse other) {
        if (other == com.module.net.Com.NetResponse.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (operateDatasBuilder_ == null) {
          if (!other.operateDatas_.isEmpty()) {
            if (operateDatas_.isEmpty()) {
              operateDatas_ = other.operateDatas_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureOperateDatasIsMutable();
              operateDatas_.addAll(other.operateDatas_);
            }
            onChanged();
          }
        } else {
          if (!other.operateDatas_.isEmpty()) {
            if (operateDatasBuilder_.isEmpty()) {
              operateDatasBuilder_.dispose();
              operateDatasBuilder_ = null;
              operateDatas_ = other.operateDatas_;
              bitField0_ = (bitField0_ & ~0x00000002);
              operateDatasBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getOperateDatasFieldBuilder() : null;
            } else {
              operateDatasBuilder_.addAllMessages(other.operateDatas_);
            }
          }
        }
        if (other.hasRetStatus()) {
          setRetStatus(other.getRetStatus());
        }
        if (other.hasStep()) {
          setStep(other.getStep());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRetStatus()) {
          
          return false;
        }
        for (int i = 0; i < getOperateDatasCount(); i++) {
          if (!getOperateDatas(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.module.net.Com.NetResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.module.net.Com.NetResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 status = 1;
      private int status_ ;
      /**
       * <code>optional int32 status = 1;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 status = 1;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>optional int32 status = 1;</code>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000001;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 status = 1;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        onChanged();
        return this;
      }

      // repeated .NetOprateData operateDatas = 2;
      private java.util.List<com.module.net.Com.NetOprateData> operateDatas_ =
        java.util.Collections.emptyList();
      private void ensureOperateDatasIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          operateDatas_ = new java.util.ArrayList<com.module.net.Com.NetOprateData>(operateDatas_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.module.net.Com.NetOprateData, com.module.net.Com.NetOprateData.Builder, com.module.net.Com.NetOprateDataOrBuilder> operateDatasBuilder_;

      /**
       * <code>repeated .NetOprateData operateDatas = 2;</code>
       *
       * <pre>
       ** 关联 
       * </pre>
       */
      public java.util.List<com.module.net.Com.NetOprateData> getOperateDatasList() {
        if (operateDatasBuilder_ == null) {
          return java.util.Collections.unmodifiableList(operateDatas_);
        } else {
          return operateDatasBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .NetOprateData operateDatas = 2;</code>
       *
       * <pre>
       ** 关联 
       * </pre>
       */
      public int getOperateDatasCount() {
        if (operateDatasBuilder_ == null) {
          return operateDatas_.size();
        } else {
          return operateDatasBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .NetOprateData operateDatas = 2;</code>
       *
       * <pre>
       ** 关联 
       * </pre>
       */
      public com.module.net.Com.NetOprateData getOperateDatas(int index) {
        if (operateDatasBuilder_ == null) {
          return operateDatas_.get(index);
        } else {
          return operateDatasBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .NetOprateData operateDatas = 2;</code>
       *
       * <pre>
       ** 关联 
       * </pre>
       */
      public Builder setOperateDatas(
          int index, com.module.net.Com.NetOprateData value) {
        if (operateDatasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOperateDatasIsMutable();
          operateDatas_.set(index, value);
          onChanged();
        } else {
          operateDatasBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NetOprateData operateDatas = 2;</code>
       *
       * <pre>
       ** 关联 
       * </pre>
       */
      public Builder setOperateDatas(
          int index, com.module.net.Com.NetOprateData.Builder builderForValue) {
        if (operateDatasBuilder_ == null) {
          ensureOperateDatasIsMutable();
          operateDatas_.set(index, builderForValue.build());
          onChanged();
        } else {
          operateDatasBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NetOprateData operateDatas = 2;</code>
       *
       * <pre>
       ** 关联 
       * </pre>
       */
      public Builder addOperateDatas(com.module.net.Com.NetOprateData value) {
        if (operateDatasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOperateDatasIsMutable();
          operateDatas_.add(value);
          onChanged();
        } else {
          operateDatasBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .NetOprateData operateDatas = 2;</code>
       *
       * <pre>
       ** 关联 
       * </pre>
       */
      public Builder addOperateDatas(
          int index, com.module.net.Com.NetOprateData value) {
        if (operateDatasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOperateDatasIsMutable();
          operateDatas_.add(index, value);
          onChanged();
        } else {
          operateDatasBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NetOprateData operateDatas = 2;</code>
       *
       * <pre>
       ** 关联 
       * </pre>
       */
      public Builder addOperateDatas(
          com.module.net.Com.NetOprateData.Builder builderForValue) {
        if (operateDatasBuilder_ == null) {
          ensureOperateDatasIsMutable();
          operateDatas_.add(builderForValue.build());
          onChanged();
        } else {
          operateDatasBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NetOprateData operateDatas = 2;</code>
       *
       * <pre>
       ** 关联 
       * </pre>
       */
      public Builder addOperateDatas(
          int index, com.module.net.Com.NetOprateData.Builder builderForValue) {
        if (operateDatasBuilder_ == null) {
          ensureOperateDatasIsMutable();
          operateDatas_.add(index, builderForValue.build());
          onChanged();
        } else {
          operateDatasBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NetOprateData operateDatas = 2;</code>
       *
       * <pre>
       ** 关联 
       * </pre>
       */
      public Builder addAllOperateDatas(
          java.lang.Iterable<? extends com.module.net.Com.NetOprateData> values) {
        if (operateDatasBuilder_ == null) {
          ensureOperateDatasIsMutable();
          super.addAll(values, operateDatas_);
          onChanged();
        } else {
          operateDatasBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .NetOprateData operateDatas = 2;</code>
       *
       * <pre>
       ** 关联 
       * </pre>
       */
      public Builder clearOperateDatas() {
        if (operateDatasBuilder_ == null) {
          operateDatas_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          operateDatasBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .NetOprateData operateDatas = 2;</code>
       *
       * <pre>
       ** 关联 
       * </pre>
       */
      public Builder removeOperateDatas(int index) {
        if (operateDatasBuilder_ == null) {
          ensureOperateDatasIsMutable();
          operateDatas_.remove(index);
          onChanged();
        } else {
          operateDatasBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .NetOprateData operateDatas = 2;</code>
       *
       * <pre>
       ** 关联 
       * </pre>
       */
      public com.module.net.Com.NetOprateData.Builder getOperateDatasBuilder(
          int index) {
        return getOperateDatasFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .NetOprateData operateDatas = 2;</code>
       *
       * <pre>
       ** 关联 
       * </pre>
       */
      public com.module.net.Com.NetOprateDataOrBuilder getOperateDatasOrBuilder(
          int index) {
        if (operateDatasBuilder_ == null) {
          return operateDatas_.get(index);  } else {
          return operateDatasBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .NetOprateData operateDatas = 2;</code>
       *
       * <pre>
       ** 关联 
       * </pre>
       */
      public java.util.List<? extends com.module.net.Com.NetOprateDataOrBuilder> 
           getOperateDatasOrBuilderList() {
        if (operateDatasBuilder_ != null) {
          return operateDatasBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(operateDatas_);
        }
      }
      /**
       * <code>repeated .NetOprateData operateDatas = 2;</code>
       *
       * <pre>
       ** 关联 
       * </pre>
       */
      public com.module.net.Com.NetOprateData.Builder addOperateDatasBuilder() {
        return getOperateDatasFieldBuilder().addBuilder(
            com.module.net.Com.NetOprateData.getDefaultInstance());
      }
      /**
       * <code>repeated .NetOprateData operateDatas = 2;</code>
       *
       * <pre>
       ** 关联 
       * </pre>
       */
      public com.module.net.Com.NetOprateData.Builder addOperateDatasBuilder(
          int index) {
        return getOperateDatasFieldBuilder().addBuilder(
            index, com.module.net.Com.NetOprateData.getDefaultInstance());
      }
      /**
       * <code>repeated .NetOprateData operateDatas = 2;</code>
       *
       * <pre>
       ** 关联 
       * </pre>
       */
      public java.util.List<com.module.net.Com.NetOprateData.Builder> 
           getOperateDatasBuilderList() {
        return getOperateDatasFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.module.net.Com.NetOprateData, com.module.net.Com.NetOprateData.Builder, com.module.net.Com.NetOprateDataOrBuilder> 
          getOperateDatasFieldBuilder() {
        if (operateDatasBuilder_ == null) {
          operateDatasBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.module.net.Com.NetOprateData, com.module.net.Com.NetOprateData.Builder, com.module.net.Com.NetOprateDataOrBuilder>(
                  operateDatas_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          operateDatas_ = null;
        }
        return operateDatasBuilder_;
      }

      // required int32 retStatus = 3;
      private int retStatus_ ;
      /**
       * <code>required int32 retStatus = 3;</code>
       *
       * <pre>
       ** 状态 
       * </pre>
       */
      public boolean hasRetStatus() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 retStatus = 3;</code>
       *
       * <pre>
       ** 状态 
       * </pre>
       */
      public int getRetStatus() {
        return retStatus_;
      }
      /**
       * <code>required int32 retStatus = 3;</code>
       *
       * <pre>
       ** 状态 
       * </pre>
       */
      public Builder setRetStatus(int value) {
        bitField0_ |= 0x00000004;
        retStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 retStatus = 3;</code>
       *
       * <pre>
       ** 状态 
       * </pre>
       */
      public Builder clearRetStatus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        retStatus_ = 0;
        onChanged();
        return this;
      }

      // optional int32 step = 4;
      private int step_ ;
      /**
       * <code>optional int32 step = 4;</code>
       */
      public boolean hasStep() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 step = 4;</code>
       */
      public int getStep() {
        return step_;
      }
      /**
       * <code>optional int32 step = 4;</code>
       */
      public Builder setStep(int value) {
        bitField0_ |= 0x00000008;
        step_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 step = 4;</code>
       */
      public Builder clearStep() {
        bitField0_ = (bitField0_ & ~0x00000008);
        step_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NetResponse)
    }

    static {
      defaultInstance = new NetResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NetResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NetOprateData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NetOprateData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NetKVData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NetKVData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NetResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NetResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017proto/Com.proto\"r\n\rNetOprateData\022\r\n\005ot" +
      "ype\030\001 \002(\005\022\013\n\003uid\030\002 \001(\005\022\014\n\004dval\030\003 \001(\005\022\014\n\004" +
      "flag\030\004 \001(\005\022\r\n\005dlist\030\005 \003(\005\022\032\n\006kvData\030\006 \003(" +
      "\0132\n.NetKVData\"0\n\tNetKVData\022\t\n\001k\030\001 \001(\005\022\t\n" +
      "\001v\030\002 \001(\005\022\r\n\005dlist\030\003 \003(\005\"d\n\013NetResponse\022\016" +
      "\n\006status\030\001 \001(\005\022$\n\014operateDatas\030\002 \003(\0132\016.N" +
      "etOprateData\022\021\n\tretStatus\030\003 \002(\005\022\014\n\004step\030" +
      "\004 \001(\005B\025\n\016com.module.netB\003Com"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_NetOprateData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_NetOprateData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NetOprateData_descriptor,
              new java.lang.String[] { "Otype", "Uid", "Dval", "Flag", "Dlist", "KvData", });
          internal_static_NetKVData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_NetKVData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NetKVData_descriptor,
              new java.lang.String[] { "K", "V", "Dlist", });
          internal_static_NetResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_NetResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NetResponse_descriptor,
              new java.lang.String[] { "Status", "OperateDatas", "RetStatus", "Step", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
