//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/NetParent.proto
namespace proto.NetParent
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NetCommond")]
  public partial class NetCommond : global::ProtoBuf.IExtensible
  {
    public NetCommond() {}
    
    private string _sn;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sn
    {
      get { return _sn; }
      set { _sn = value; }
    }
    private byte[] _obj;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"obj", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] obj
    {
      get { return _obj; }
      set { _obj = value; }
    }
    private int _seq;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"seq", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seq
    {
      get { return _seq; }
      set { _seq = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NetError")]
  public partial class NetError : global::ProtoBuf.IExtensible
  {
    public NetError() {}
    
    private int _errorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _paramters = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"paramters", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> paramters
    {
      get { return _paramters; }
    }
  
    private int _seq = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"seq", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int seq
    {
      get { return _seq; }
      set { _seq = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NetServerCommond")]
  public partial class NetServerCommond : global::ProtoBuf.IExtensible
  {
    public NetServerCommond() {}
    
    private int _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private byte[] _obj;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"obj", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] obj
    {
      get { return _obj; }
      set { _obj = value; }
    }
    private string _sn = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sn
    {
      get { return _sn; }
      set { _sn = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}